### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/pkgbuild-roundedsbe-git#1]
Should this be renamed to pkgbuild-roundedsbe-git, since the upstream project is RoundedSBE?

**Comment by alexjp** [comment]
hey sorry for the delay !!! Yes ! how do you want to proceed ? Can I do it ?

**Comment by xiota** [comment]
No problem.  Don't know if I have permissions necessary to rename.  Since you maintain this, probably better for you to rename, that way there's no confusion later.  As far as I can tell, this isn't in chaotic-aur/packages (yet?), so nothing to change there.

**Comment by alexjp** [comment]
Did rename : https://github.com/chaotic-aur/pkgbuild-roundedsbe-git

and added the package here: https://github.com/chaotic-aur/packages/blob/bbd41578fdf8b55c9f5f888fb24a3101037e63b2/dragon-cluster/nightly.txt#L87
